apiVersion: v2
name: lottery
description: A Helm chart for the Lottery application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - lottery
  - django
  - nextjs
  - celery
maintainers:
  - name: Your Name
    email: your.email@example.com
