# Generated by Django 5.2.4 on 2025-07-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("number", models.IntegerField(default=1)),
                (
                    "drawtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottery.drawtype",
                    ),
                ),
            ],
        ),
    ]
