# Generated by Django 5.2.4 on 2025-07-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_password_reset_expires_and_more"),
        ("lottery", "0002_prize"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prize",
            options={"ordering": ("drawtype", "-amount", "number")},
        ),
        migrations.AlterField(
            model_name="prize",
            name="drawtype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prizes",
                to="lottery.drawtype",
            ),
        ),
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "drawtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draws",
                        to="lottery.drawtype",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to="accounts.account",
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to="lottery.draw",
                    ),
                ),
            ],
            options={
                "ordering": ("draw", "account"),
            },
        ),
    ]
