# Generated by Django 5.2.4 on 2025-07-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lottery",
            "0003_alter_prize_options_alter_prize_drawtype_draw_ballot",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="prize",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ballots",
                to="lottery.prize",
            ),
        ),
        migrations.AddField(
            model_name="draw",
            name="closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
