# Network policies for the lottery application - following security best practices
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lottery-backend-policy
  namespace: lottery
spec:
  podSelector:
    matchLabels:
      app: lottery-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from ingress-nginx controller only
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow egress to database (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/component: primary
    ports:
    - protocol: TCP
      port: 5432
  # Allow egress to Redis (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: master
    ports:
    - protocol: TCP
      port: 6379
  # Allow DNS resolution (kube-system namespace only)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lottery-frontend-policy
  namespace: lottery
spec:
  podSelector:
    matchLabels:
      app: lottery-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from ingress-nginx controller only
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow egress to backend API (specific port)
  - to:
    - podSelector:
        matchLabels:
          app: lottery-backend
    ports:
    - protocol: TCP
      port: 8000
  # Allow DNS resolution (kube-system namespace only)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lottery-celery-policy
  namespace: lottery
spec:
  podSelector:
    matchLabels:
      app: lottery-celery-worker
  policyTypes:
  - Egress
  egress:
  # Allow egress to database (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/component: primary
    ports:
    - protocol: TCP
      port: 5432
  # Allow egress to Redis (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: master
    ports:
    - protocol: TCP
      port: 6379
  # Allow DNS resolution (kube-system namespace only)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# Network policy for Celery Beat (separate from worker)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lottery-celery-beat-policy
  namespace: lottery
spec:
  podSelector:
    matchLabels:
      app: lottery-celery-beat
  policyTypes:
  - Egress
  egress:
  # Allow egress to database (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/component: primary
    ports:
    - protocol: TCP
      port: 5432
  # Allow egress to Redis (specific port)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: master
    ports:
    - protocol: TCP
      port: 6379
  # Allow DNS resolution (kube-system namespace only)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53 
