name: 'Setup Docker Environment'
description: 'Setup Docker Buildx, login to registry, and update compose file'

inputs:
  registry-password:
    description: 'Registry password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ inputs.registry-password }}

    - name: Update compose file to use registry images
      shell: bash
      run: python3 scripts/update-compose.py ${{ env.REGISTRY }} ${{ github.sha }} 
