name: "Setup Docker Environment"
description: "Setup Docker Buildx, login to GitHub Container Registry, and update compose file"

inputs:
  ghcr-access-token:
    description: "Personal access token (classic) for GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ inputs.ghcr-access-token }}

    - name: Update compose file to use registry images
      shell: bash
      run: python3 scripts/update-compose.py ${{ env.COMMIT_SHA }}
