name: CI/CD Pipeline

on:
  push:
    # branches: [main, fix/*]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ganzevoort
  BACKEND_IMAGE: ghcr.io/ganzevoort/bynderlottery/backend
  FRONTEND_IMAGE: ghcr.io/ganzevoort/bynderlottery/frontend
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

defaults:
  run:
    shell: bash

jobs:
  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker
        with:
          ghcr-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Wait for backend image (PR only)
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/wait-for-registry-image
        with:
          image: ${{ env.BACKEND_IMAGE }}:build-${{ env.COMMIT_SHA }}
          commit-sha: ${{ env.COMMIT_SHA }}

      - name: Build and push backend production image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:build-${{ env.COMMIT_SHA }}
          target: production
          cache-from: |
            type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max

      - name: Backend linters and unittests
        # These tests are included as a build target.
        # Using separate cache to avoid conflicts with production build layers.
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: ${{ env.BACKEND_IMAGE }}:tester-${{ env.COMMIT_SHA }}
          target: tester
          cache-from: |
            type=registry,ref=${{ env.BACKEND_IMAGE }}:tester-cache
          cache-to: |
            type=registry,ref=${{ env.BACKEND_IMAGE }}:tester-cache,mode=max

  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker
        with:
          ghcr-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Wait for frontend image (PR only)
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/wait-for-registry-image
        with:
          image: ${{ env.FRONTEND_IMAGE }}:build-${{ env.COMMIT_SHA }}
          commit-sha: ${{ env.COMMIT_SHA }}

      - name: Build and push frontend production image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:build-${{ env.COMMIT_SHA }}
          target: production
          cache-from: |
            type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

      - name: Frontend linters and unittests
        # These tests are included as a build target.
        # Using separate cache to avoid conflicts with production build layers.
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: ${{ env.FRONTEND_IMAGE }}:tester-${{ env.COMMIT_SHA }}
          target: tester
          cache-from: |
            type=registry,ref=${{ env.FRONTEND_IMAGE }}:tester-cache
          cache-to: |
            type=registry,ref=${{ env.FRONTEND_IMAGE }}:tester-cache,mode=max

  test-integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker
        with:
          ghcr-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Show compose.test.yaml
        run: cat compose.test.yaml

      - name: Pull test images
        run: docker compose -f compose.test.yaml pull --quiet

      - name: Start the test containers
        run: docker compose -f compose.test.yaml up -d

      - name: Run integration test suite
        run: docker compose -f compose.test.yaml exec cypress cypress run --spec "e2e/tests/**/*.cy.ts"

      - name: Stop the test containers
        run: docker compose -f compose.test.yaml down

  demo:
    name: Create Demo Video
    runs-on: ubuntu-latest
    needs: [test-integration]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker
        with:
          ghcr-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Pull test images
        run: docker compose -f compose.test.yaml pull --quiet

      - name: Start the test containers
        run: docker compose -f compose.test.yaml up -d

      - name: Run demo suite to create a video
        run: docker compose -f compose.test.yaml exec cypress cypress run --spec "e2e/demo/**/*.cy.ts"

      - name: Stop the test containers
        run: docker compose -f compose.test.yaml down

      - name: Upload demo video artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-videos
          path: cypress/videos/
          retention-days: 30

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test-integration]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "Kubeconfig configured successfully"
          kubectl cluster-info

      - name: Set up crane
        uses: imjasonh/setup-crane@v0.3

      - name: Retag images as latest
        run: |
          # Authenticate with GitHub Container Registry using personal access token
          echo ${{ secrets.GHCR_ACCESS_TOKEN }} | crane auth login ghcr.io -u ${{ env.REGISTRY_USERNAME }} --password-stdin
          # Copy build images to latest tags for deployment
          crane copy ${{ env.BACKEND_IMAGE }}:build-${{ env.COMMIT_SHA }} ${{ env.BACKEND_IMAGE }}:latest
          crane copy ${{ env.FRONTEND_IMAGE }}:build-${{ env.COMMIT_SHA }} ${{ env.FRONTEND_IMAGE }}:latest

      - name: Deploy to Kubernetes
        run: |
          # Apply lottery namespace resources
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/configmaps.yaml -f k8s/deployments.yaml -f k8s/services.yaml -f k8s/ingress.yaml -f k8s/network-policies.yaml -f k8s/hpa.yaml -f k8s/backup-job.yaml -n lottery

          # Apply docker-registry namespace resources
          kubectl apply -f k8s/registry-deployment.yaml -n docker-registry

          # Restart lottery deployments
          kubectl rollout restart deployment lottery-backend lottery-frontend lottery-celery-worker lottery-celery-beat -n lottery
          kubectl rollout status deployment lottery-backend lottery-frontend lottery-celery-worker lottery-celery-beat -n lottery

      - name: Verify deployment
        run: |
          kubectl get pods -n lottery
          kubectl get services -n lottery
